//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnaliticaFiltrosPYG
    {
        public string empresa { get; set; }
        public int id { get; set; }
        public string usuario { get; set; }
        public int fkejercicio { get; set; }
        public string guia { get; set; }
        public Nullable<System.DateTime> fechaCalculo { get; set; }
        public string usuario_ant { get; set; }
        public Nullable<int> fkejercicio_ant { get; set; }
    }
}
