//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogStockSeguridad
    {
        public string empresa { get; set; }
        public string codarticulo { get; set; }
        public string descripcionarticulo { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string documento { get; set; }
        public string codigounidad { get; set; }
        public Nullable<double> stockminimo { get; set; }
        public Nullable<double> stockactual { get; set; }
        public Nullable<double> pedidooptimo { get; set; }
        public Nullable<int> stockseguridad { get; set; }
        public string almacen { get; set; }
    
        public virtual Articulos Articulos { get; set; }
    }
}
