//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreciosEspeciales
    {
        public string empresa { get; set; }
        public int id { get; set; }
        public string fkclientes { get; set; }
        public string fkarticulo { get; set; }
        public Nullable<System.DateTime> fechavalidez { get; set; }
        public double precio { get; set; }
        public Nullable<double> descuento { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
