//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroIVARepercutidoRectificadas
    {
        public string empresa { get; set; }
        public int fkregistros { get; set; }
        public int id { get; set; }
        public string facturaemisor { get; set; }
        public Nullable<System.DateTime> fechaexpedemisor { get; set; }
    
        public virtual RegistroIVARepercutido RegistroIVARepercutido { get; set; }
    }
}
