//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroIVARepercutidoSumaTotales
    {
        public string empresa { get; set; }
        public int fkregistros { get; set; }
        public int id { get; set; }
        public Nullable<double> baseretencion { get; set; }
        public Nullable<double> porcentajeretencion { get; set; }
        public Nullable<double> importeretencion { get; set; }
        public Nullable<double> operacionesexluidasbi { get; set; }
        public Nullable<double> totalfactura { get; set; }
        public Nullable<int> decimalesmonedas { get; set; }
    
        public virtual RegistroIVARepercutido RegistroIVARepercutido { get; set; }
    }
}
