//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlbaranesCompras {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlbaranesCompras() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.AlbaranesCompras", typeof(AlbaranesCompras).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acabado desde.
        /// </summary>
        public static string AcabadosDesde {
            get {
                return ResourceManager.GetString("AcabadosDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acabado hasta.
        /// </summary>
        public static string AcabadosHasta {
            get {
                return ResourceManager.GetString("AcabadosHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albarán de compra.
        /// </summary>
        public static string albaranescompras {
            get {
                return ResourceManager.GetString("albaranescompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho.
        /// </summary>
        public static string Ancho {
            get {
                return ResourceManager.GetString("Ancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho Entrada.
        /// </summary>
        public static string AnchoEntrada {
            get {
                return ResourceManager.GetString("AnchoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho Prod..
        /// </summary>
        public static string AnchoProduccion {
            get {
                return ResourceManager.GetString("AnchoProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho Salida.
        /// </summary>
        public static string AnchoSalida {
            get {
                return ResourceManager.GetString("AnchoSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistente Remedir / Propiedades.
        /// </summary>
        public static string AsistenteRemedir {
            get {
                return ResourceManager.GetString("AsistenteRemedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base.
        /// </summary>
        public static string Basetotal {
            get {
                return ResourceManager.GetString("Basetotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bruto.
        /// </summary>
        public static string BrutoTotal {
            get {
                return ResourceManager.GetString("BrutoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº de bultos.
        /// </summary>
        public static string Bultos {
            get {
                return ResourceManager.GetString("Bultos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bundle.
        /// </summary>
        public static string Bundle {
            get {
                return ResourceManager.GetString("Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caja.
        /// </summary>
        public static string Caja {
            get {
                return ResourceManager.GetString("Caja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio adicional.
        /// </summary>
        public static string Cambioadicional {
            get {
                return ResourceManager.GetString("Cambioadicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canal.
        /// </summary>
        public static string Canal {
            get {
                return ResourceManager.GetString("Canal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad Disponible.
        /// </summary>
        public static string CantidadDisponible {
            get {
                return ResourceManager.GetString("CantidadDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad Entrada.
        /// </summary>
        public static string CantidadEntrada {
            get {
                return ResourceManager.GetString("CantidadEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C. servida.
        /// </summary>
        public static string Cantidadpedida {
            get {
                return ResourceManager.GetString("Cantidadpedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad Prod..
        /// </summary>
        public static string CantidadProduccion {
            get {
                return ResourceManager.GetString("CantidadProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad Salida.
        /// </summary>
        public static string CantidadSalida {
            get {
                return ResourceManager.GetString("CantidadSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Característica desde.
        /// </summary>
        public static string CaracteristicasDesde {
            get {
                return ResourceManager.GetString("CaracteristicasDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Característica hasta.
        /// </summary>
        public static string CaracteristicasHasta {
            get {
                return ResourceManager.GetString("CaracteristicasHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carta de crédito.
        /// </summary>
        public static string Cartacredito {
            get {
                return ResourceManager.GetString("Cartacredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C.P..
        /// </summary>
        public static string Clientecp {
            get {
                return ResourceManager.GetString("Clientecp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente desde.
        /// </summary>
        public static string ClienteDesde {
            get {
                return ResourceManager.GetString("ClienteDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Clientedireccion {
            get {
                return ResourceManager.GetString("Clientedireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Clienteemail {
            get {
                return ResourceManager.GetString("Clienteemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax.
        /// </summary>
        public static string Clientefax {
            get {
                return ResourceManager.GetString("Clientefax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente hasta.
        /// </summary>
        public static string ClienteHasta {
            get {
                return ResourceManager.GetString("ClienteHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIF / CIF.
        /// </summary>
        public static string Clientenif {
            get {
                return ResourceManager.GetString("Clientenif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string Clientepais {
            get {
                return ResourceManager.GetString("Clientepais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Población.
        /// </summary>
        public static string Clientepoblacion {
            get {
                return ResourceManager.GetString("Clientepoblacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string Clienteprovincia {
            get {
                return ResourceManager.GetString("Clienteprovincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Clientetelefono {
            get {
                return ResourceManager.GetString("Clientetelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cód. Lote.
        /// </summary>
        public static string CodigoLote {
            get {
                return ResourceManager.GetString("CodigoLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Com..
        /// </summary>
        public static string Comisionagente {
            get {
                return ResourceManager.GetString("Comisionagente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Com..
        /// </summary>
        public static string Comisioncomercial {
            get {
                return ResourceManager.GetString("Comisioncomercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conductor.
        /// </summary>
        public static string Conductor {
            get {
                return ResourceManager.GetString("Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Confianza venta.
        /// </summary>
        public static string Confianza {
            get {
                return ResourceManager.GetString("Confianza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenedor.
        /// </summary>
        public static string Contenedor {
            get {
                return ResourceManager.GetString("Contenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenedores.
        /// </summary>
        public static string Contenedores {
            get {
                return ResourceManager.GetString("Contenedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste adicional: material.
        /// </summary>
        public static string Costeadicionalmaterial {
            get {
                return ResourceManager.GetString("Costeadicionalmaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste adicional: otro.
        /// </summary>
        public static string Costeadicionalotro {
            get {
                return ResourceManager.GetString("Costeadicionalotro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste adicional: portes.
        /// </summary>
        public static string Costeadicionalportes {
            get {
                return ResourceManager.GetString("Costeadicionalportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste adicional: variable.
        /// </summary>
        public static string Costeadicionalvariable {
            get {
                return ResourceManager.GetString("Costeadicionalvariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste materiales.
        /// </summary>
        public static string Costemateriales {
            get {
                return ResourceManager.GetString("Costemateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste total.
        /// </summary>
        public static string CosteNeto {
            get {
                return ResourceManager.GetString("CosteNeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste portes.
        /// </summary>
        public static string Costeportes {
            get {
                return ResourceManager.GetString("Costeportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costes adicionales.
        /// </summary>
        public static string CostesAdicionales {
            get {
                return ResourceManager.GetString("CostesAdicionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costes x UM (Metros entrada).
        /// </summary>
        public static string Costeumentrada {
            get {
                return ResourceManager.GetString("Costeumentrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costes x UM (Metros producción).
        /// </summary>
        public static string Costeumproduccion {
            get {
                return ResourceManager.GetString("Costeumproduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste x m2.
        /// </summary>
        public static string Costexm2 {
            get {
                return ResourceManager.GetString("Costexm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste x m3.
        /// </summary>
        public static string Costexm3 {
            get {
                return ResourceManager.GetString("Costexm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuota de IVA.
        /// </summary>
        public static string Cuotaiva {
            get {
                return ResourceManager.GetString("Cuotaiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuota R.E..
        /// </summary>
        public static string Cuotarecargoequivalencia {
            get {
                return ResourceManager.GetString("Cuotarecargoequivalencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incoterm.
        /// </summary>
        public static string Descripcionincoterm {
            get {
                return ResourceManager.GetString("Descripcionincoterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde lote.
        /// </summary>
        public static string DesdeLote {
            get {
                return ResourceManager.GetString("DesdeLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde recep. stock.
        /// </summary>
        public static string Desderecepcionstock {
            get {
                return ResourceManager.GetString("Desderecepcionstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada de stock.
        /// </summary>
        public static string EntradaStock {
            get {
                return ResourceManager.GetString("EntradaStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones envío.
        /// </summary>
        public static string Envio {
            get {
                return ResourceManager.GetString("Envio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar el albarán porque ya está facturado.
        /// </summary>
        public static string ErrorAlbaranFacturado {
            get {
                return ResourceManager.GetString("ErrorAlbaranFacturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de nueva línea no puede ser igual o superior a la de la línea que vamos a dividir.
        /// </summary>
        public static string ErrorDividirLineaCantidadCero {
            get {
                return ResourceManager.GetString("ErrorDividirLineaCantidadCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha del documento no corresponde con la fecha del ejercicio del documento.
        /// </summary>
        public static string ErrorFechaEjercicio {
            get {
                return ResourceManager.GetString("ErrorFechaEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generación de lotes fallida.
        /// </summary>
        public static string ErrorGestionLotes {
            get {
                return ResourceManager.GetString("ErrorGestionLotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar el pedido porque tiene líneas asociadas a uno o varios albaranes.
        /// </summary>
        public static string ErrorLineasAsociadasAAlbaranes {
            get {
                return ResourceManager.GetString("ErrorLineasAsociadasAAlbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede agregar el artículo porque ya existe uno con el mismo numero de Lote.
        /// </summary>
        public static string ErrorLoteRepetido {
            get {
                return ResourceManager.GetString("ErrorLoteRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La moneda de la serie no coincide con la del cliente.
        /// </summary>
        public static string ErrorMonedaClienteSerie {
            get {
                return ResourceManager.GetString("ErrorMonedaClienteSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede importar el pedido porque no tiene líneas pendientes de servir.
        /// </summary>
        public static string ErrorSinCantidadPendiente {
            get {
                return ResourceManager.GetString("ErrorSinCantidadPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia desde.
        /// </summary>
        public static string FamiliaDesde {
            get {
                return ResourceManager.GetString("FamiliaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia hasta.
        /// </summary>
        public static string FamiliaHasta {
            get {
                return ResourceManager.GetString("FamiliaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia material.
        /// </summary>
        public static string FamiliaMateriales {
            get {
                return ResourceManager.GetString("FamiliaMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha desde.
        /// </summary>
        public static string FechaDesde {
            get {
                return ResourceManager.GetString("FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Fechadocumento {
            get {
                return ResourceManager.GetString("Fechadocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha documento proveedor.
        /// </summary>
        public static string Fechadocumentoproveedor {
            get {
                return ResourceManager.GetString("Fechadocumentoproveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F. Entrega.
        /// </summary>
        public static string Fechaentrega {
            get {
                return ResourceManager.GetString("Fechaentrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha hasta.
        /// </summary>
        public static string FechaHasta {
            get {
                return ResourceManager.GetString("FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F. Revisión.
        /// </summary>
        public static string Fecharevision {
            get {
                return ResourceManager.GetString("Fecharevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F. Validez.
        /// </summary>
        public static string Fechavalidez {
            get {
                return ResourceManager.GetString("Fechavalidez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente.
        /// </summary>
        public static string Fkagentes {
            get {
                return ResourceManager.GetString("Fkagentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacén.
        /// </summary>
        public static string Fkalmacen {
            get {
                return ResourceManager.GetString("Fkalmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cód. artículo.
        /// </summary>
        public static string Fkarticulos {
            get {
                return ResourceManager.GetString("Fkarticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo desde.
        /// </summary>
        public static string FkarticulosDesde {
            get {
                return ResourceManager.GetString("FkarticulosDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo hasta.
        /// </summary>
        public static string FkarticulosHasta {
            get {
                return ResourceManager.GetString("FkarticulosHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string Fkbancosmandatos {
            get {
                return ResourceManager.GetString("Fkbancosmandatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificación comercial.
        /// </summary>
        public static string Fkcalificacioncomercial {
            get {
                return ResourceManager.GetString("Fkcalificacioncomercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string Fkclientes {
            get {
                return ResourceManager.GetString("Fkclientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente reserva.
        /// </summary>
        public static string Fkclientesreserva {
            get {
                return ResourceManager.GetString("Fkclientesreserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comercial.
        /// </summary>
        public static string Fkcomerciales {
            get {
                return ResourceManager.GetString("Fkcomerciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Fkcontadores {
            get {
                return ResourceManager.GetString("Fkcontadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tesoreria.
        /// </summary>
        public static string Fkcuentastesoreria {
            get {
                return ResourceManager.GetString("Fkcuentastesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de facturación.
        /// </summary>
        public static string Fkdireccionfacturacion {
            get {
                return ResourceManager.GetString("Fkdireccionfacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejercicio.
        /// </summary>
        public static string Fkejercicio {
            get {
                return ResourceManager.GetString("Fkejercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia artículo.
        /// </summary>
        public static string Fkfamilias {
            get {
                return ResourceManager.GetString("Fkfamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de pago.
        /// </summary>
        public static string Fkformaspago {
            get {
                return ResourceManager.GetString("Fkformaspago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencias material.
        /// </summary>
        public static string Fkincidenciasmaterial {
            get {
                return ResourceManager.GetString("Fkincidenciasmaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda.
        /// </summary>
        public static string Fkmonedas {
            get {
                return ResourceManager.GetString("Fkmonedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo de devolución.
        /// </summary>
        public static string Fkmotivosdevolucion {
            get {
                return ResourceManager.GetString("Fkmotivosdevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obra.
        /// </summary>
        public static string Fkobras {
            get {
                return ResourceManager.GetString("Fkobras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operario.
        /// </summary>
        public static string Fkoperarios {
            get {
                return ResourceManager.GetString("Fkoperarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operador de transporte.
        /// </summary>
        public static string Fkoperariostransporte {
            get {
                return ResourceManager.GetString("Fkoperariostransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string Fkproveedores {
            get {
                return ResourceManager.GetString("Fkproveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regimen IVA.
        /// </summary>
        public static string Fkregimeniva {
            get {
                return ResourceManager.GetString("Fkregimeniva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie.
        /// </summary>
        public static string Fkseries {
            get {
                return ResourceManager.GetString("Fkseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de grano.
        /// </summary>
        public static string Fktipograno {
            get {
                return ResourceManager.GetString("Fktipograno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de albarán.
        /// </summary>
        public static string Fktiposalbaranes {
            get {
                return ResourceManager.GetString("Fktiposalbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA.
        /// </summary>
        public static string Fktiposiva {
            get {
                return ResourceManager.GetString("Fktiposiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tono de material.
        /// </summary>
        public static string Fktonomaterial {
            get {
                return ResourceManager.GetString("Fktonomaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportista.
        /// </summary>
        public static string Fktransportista {
            get {
                return ResourceManager.GetString("Fktransportista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad medida.
        /// </summary>
        public static string Fkunidades {
            get {
                return ResourceManager.GetString("Fkunidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variedades de material.
        /// </summary>
        public static string Fkvariedades {
            get {
                return ResourceManager.GetString("Fkvariedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona.
        /// </summary>
        public static string Fkzonas {
            get {
                return ResourceManager.GetString("Fkzonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosor desde.
        /// </summary>
        public static string GrosoresDesde {
            get {
                return ResourceManager.GetString("GrosoresDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosor hasta.
        /// </summary>
        public static string GrosoresHasta {
            get {
                return ResourceManager.GetString("GrosoresHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grueso.
        /// </summary>
        public static string Grueso {
            get {
                return ResourceManager.GetString("Grueso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grueso Entrada.
        /// </summary>
        public static string GruesoEntrada {
            get {
                return ResourceManager.GetString("GruesoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grueso Prod..
        /// </summary>
        public static string GruesoProduccion {
            get {
                return ResourceManager.GetString("GruesoProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grueso Salida.
        /// </summary>
        public static string GruesoSalida {
            get {
                return ResourceManager.GetString("GruesoSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta lote.
        /// </summary>
        public static string HastaLote {
            get {
                return ResourceManager.GetString("HastaLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta recep. stock.
        /// </summary>
        public static string Hastarecepcionstock {
            get {
                return ResourceManager.GetString("Hastarecepcionstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        public static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Identificadorsegmento {
            get {
                return ResourceManager.GetString("Identificadorsegmento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe.
        /// </summary>
        public static string Importe {
            get {
                return ResourceManager.GetString("Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        public static string ImporteBase {
            get {
                return ResourceManager.GetString("ImporteBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base.
        /// </summary>
        public static string Importebaseimponible {
            get {
                return ResourceManager.GetString("Importebaseimponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe bruto.
        /// </summary>
        public static string Importebruto {
            get {
                return ResourceManager.GetString("Importebruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe descuento.
        /// </summary>
        public static string Importedescuento {
            get {
                return ResourceManager.GetString("Importedescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imp. Dto. Cial..
        /// </summary>
        public static string Importedescuentocomercial {
            get {
                return ResourceManager.GetString("Importedescuentocomercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imp. Dtp. P.P..
        /// </summary>
        public static string Importedescuentoprontopago {
            get {
                return ResourceManager.GetString("Importedescuentoprontopago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe fijo.
        /// </summary>
        public static string Importefijo {
            get {
                return ResourceManager.GetString("Importefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe neto linea.
        /// </summary>
        public static string Importenetolinea {
            get {
                return ResourceManager.GetString("Importenetolinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe portes.
        /// </summary>
        public static string Importeportes {
            get {
                return ResourceManager.GetString("Importeportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Importetotaldoc {
            get {
                return ResourceManager.GetString("Importetotaldoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total (Moneda base).
        /// </summary>
        public static string Importetotalmonedabase {
            get {
                return ResourceManager.GetString("Importetotalmonedabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cód. Incoterm.
        /// </summary>
        public static string Incoterm {
            get {
                return ResourceManager.GetString("Incoterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Largo.
        /// </summary>
        public static string Largo {
            get {
                return ResourceManager.GetString("Largo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Largo Entrada.
        /// </summary>
        public static string LargoEntrada {
            get {
                return ResourceManager.GetString("LargoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Largo Prod..
        /// </summary>
        public static string LargoProduccion {
            get {
                return ResourceManager.GetString("LargoProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Largo Salida.
        /// </summary>
        public static string LargoSalida {
            get {
                return ResourceManager.GetString("LargoSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo.
        /// </summary>
        public static string LblAgrupadoArticulo {
            get {
                return ResourceManager.GetString("LblAgrupadoArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo, Lote.
        /// </summary>
        public static string LblAgrupadoArticuloLote {
            get {
                return ResourceManager.GetString("LblAgrupadoArticuloLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo, Lote, Medidas.
        /// </summary>
        public static string LblAgrupadoArticuloLoteMedidas {
            get {
                return ResourceManager.GetString("LblAgrupadoArticuloLoteMedidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo, Medidas.
        /// </summary>
        public static string LblAgrupadoArticuloMedidas {
            get {
                return ResourceManager.GetString("LblAgrupadoArticuloMedidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo artículos bajo mínimo.
        /// </summary>
        public static string LblArticulos {
            get {
                return ResourceManager.GetString("LblArticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar direcciones asociadas al Cliente.
        /// </summary>
        public static string LblBuscarDireccion {
            get {
                return ResourceManager.GetString("LblBuscarDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar direcciones asociadas al Proveedor.
        /// </summary>
        public static string LblBuscarDireccionProveedor {
            get {
                return ResourceManager.GetString("LblBuscarDireccionProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuentos de cabecera.
        /// </summary>
        public static string LblDescuentosCabeceras {
            get {
                return ResourceManager.GetString("LblDescuentosCabeceras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detallado por.
        /// </summary>
        public static string LblDetallepor {
            get {
                return ResourceManager.GetString("LblDetallepor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar albarán de devolución.
        /// </summary>
        public static string LblGenerarDevolucion {
            get {
                return ResourceManager.GetString("LblGenerarDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar devolución.
        /// </summary>
        public static string LblGestionDevoluciones {
            get {
                return ResourceManager.GetString("LblGestionDevoluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar líneas de pedidos.
        /// </summary>
        public static string LblImportar {
            get {
                return ResourceManager.GetString("LblImportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        public static string LblMostrar {
            get {
                return ResourceManager.GetString("LblMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin agrupar.
        /// </summary>
        public static string LblSinAgrupar {
            get {
                return ResourceManager.GetString("LblSinAgrupar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin detallar.
        /// </summary>
        public static string LblSindetallar {
            get {
                return ResourceManager.GetString("LblSindetallar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos (Artículos con stock mínimo indicado).
        /// </summary>
        public static string LblTodos {
            get {
                return ResourceManager.GetString("LblTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Líneas del presupuesto.
        /// </summary>
        public static string Lineas {
            get {
                return ResourceManager.GetString("Lineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote.
        /// </summary>
        public static string Lote {
            get {
                return ResourceManager.GetString("Lote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote Automático.
        /// </summary>
        public static string LoteAutomatico {
            get {
                return ResourceManager.GetString("LoteAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote desde.
        /// </summary>
        public static string LoteDesde {
            get {
                return ResourceManager.GetString("LoteDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote hasta.
        /// </summary>
        public static string LoteHasta {
            get {
                return ResourceManager.GetString("LoteHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote proveedor.
        /// </summary>
        public static string Loteproveedor {
            get {
                return ResourceManager.GetString("Loteproveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material desde.
        /// </summary>
        public static string MaterialesDesde {
            get {
                return ResourceManager.GetString("MaterialesDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material hastas.
        /// </summary>
        public static string MaterialesHasta {
            get {
                return ResourceManager.GetString("MaterialesHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula.
        /// </summary>
        public static string Matricula {
            get {
                return ResourceManager.GetString("Matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metros.
        /// </summary>
        public static string Metros {
            get {
                return ResourceManager.GetString("Metros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metros Disp..
        /// </summary>
        public static string MetrosDisponibles {
            get {
                return ResourceManager.GetString("MetrosDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metros Entrada.
        /// </summary>
        public static string MetrosEntrada {
            get {
                return ResourceManager.GetString("MetrosEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metros Prod..
        /// </summary>
        public static string MetrosProduccion {
            get {
                return ResourceManager.GetString("MetrosProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metros Salida.
        /// </summary>
        public static string MetrosSalida {
            get {
                return ResourceManager.GetString("MetrosSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio neto de compra.
        /// </summary>
        public static string Netocompra {
            get {
                return ResourceManager.GetString("Netocompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombrecliente {
            get {
                return ResourceManager.GetString("Nombrecliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombreproveedor {
            get {
                return ResourceManager.GetString("Nombreproveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre transportista.
        /// </summary>
        public static string Nombretransportista {
            get {
                return ResourceManager.GetString("Nombretransportista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Notas {
            get {
                return ResourceManager.GetString("Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo ancho (m).
        /// </summary>
        public static string Nuevoancho {
            get {
                return ResourceManager.GetString("Nuevoancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo grueso (m).
        /// </summary>
        public static string Nuevogrueso {
            get {
                return ResourceManager.GetString("Nuevogrueso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo largo (m).
        /// </summary>
        public static string Nuevolargo {
            get {
                return ResourceManager.GetString("Nuevolargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia documento proveedor.
        /// </summary>
        public static string Numerodocumentoproveedor {
            get {
                return ResourceManager.GetString("Numerodocumentoproveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros.
        /// </summary>
        public static string Otros {
            get {
                return ResourceManager.GetString("Otros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        public static string Peso {
            get {
                return ResourceManager.GetString("Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso bruto.
        /// </summary>
        public static string Pesobruto {
            get {
                return ResourceManager.GetString("Pesobruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso neto.
        /// </summary>
        public static string Pesoneto {
            get {
                return ResourceManager.GetString("Pesoneto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        public static string Pesoum {
            get {
                return ResourceManager.GetString("Pesoum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje.
        /// </summary>
        public static string Porcentaje {
            get {
                return ResourceManager.GetString("Porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Desc..
        /// </summary>
        public static string Porcentajedescuento {
            get {
                return ResourceManager.GetString("Porcentajedescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Dto. Cial..
        /// </summary>
        public static string Porcentajedescuentocomercial {
            get {
                return ResourceManager.GetString("Porcentajedescuentocomercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Dto. P.P..
        /// </summary>
        public static string Porcentajedescuentoprontopago {
            get {
                return ResourceManager.GetString("Porcentajedescuentoprontopago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % IVA.
        /// </summary>
        public static string Porcentajeiva {
            get {
                return ResourceManager.GetString("Porcentajeiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % R.E..
        /// </summary>
        public static string Porcentajerecargoequivalencia {
            get {
                return ResourceManager.GetString("Porcentajerecargoequivalencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portes.
        /// </summary>
        public static string Portes {
            get {
                return ResourceManager.GetString("Portes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio anterior.
        /// </summary>
        public static string Precioanterior {
            get {
                return ResourceManager.GetString("Precioanterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio valoración stock.
        /// </summary>
        public static string Preciovaloracion {
            get {
                return ResourceManager.GetString("Preciovaloracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C.P..
        /// </summary>
        public static string Proveedorcp {
            get {
                return ResourceManager.GetString("Proveedorcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor desde.
        /// </summary>
        public static string ProveedorDesde {
            get {
                return ResourceManager.GetString("ProveedorDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Proveedordireccion {
            get {
                return ResourceManager.GetString("Proveedordireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Proveedoremail {
            get {
                return ResourceManager.GetString("Proveedoremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax.
        /// </summary>
        public static string Proveedorfax {
            get {
                return ResourceManager.GetString("Proveedorfax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor hasta.
        /// </summary>
        public static string ProveedorHasta {
            get {
                return ResourceManager.GetString("ProveedorHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIF / CIF.
        /// </summary>
        public static string Proveedornif {
            get {
                return ResourceManager.GetString("Proveedornif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string Proveedorpais {
            get {
                return ResourceManager.GetString("Proveedorpais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Población.
        /// </summary>
        public static string Proveedorpoblacion {
            get {
                return ResourceManager.GetString("Proveedorpoblacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string Proveedorprovincia {
            get {
                return ResourceManager.GetString("Proveedorprovincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Proveedortelefono {
            get {
                return ResourceManager.GetString("Proveedortelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ref. Desde.
        /// </summary>
        public static string RefereciaDesde {
            get {
                return ResourceManager.GetString("RefereciaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ref. Hasta.
        /// </summary>
        public static string RefereciaHasta {
            get {
                return ResourceManager.GetString("RefereciaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ref. de documento.
        /// </summary>
        public static string Referenciadocumento {
            get {
                return ResourceManager.GetString("Referenciadocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remedir / Propiedades.
        /// </summary>
        public static string Remedirlotes {
            get {
                return ResourceManager.GetString("Remedirlotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revisión.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sección.
        /// </summary>
        public static string Seccion {
            get {
                return ResourceManager.GetString("Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sello.
        /// </summary>
        public static string Sello {
            get {
                return ResourceManager.GetString("Sello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series.
        /// </summary>
        public static string SeriesListado {
            get {
                return ResourceManager.GetString("SeriesListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sumar (cm).
        /// </summary>
        public static string Sumarancho {
            get {
                return ResourceManager.GetString("Sumarancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sumar (cm).
        /// </summary>
        public static string Sumargrueso {
            get {
                return ResourceManager.GetString("Sumargrueso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sumar (cm).
        /// </summary>
        public static string Sumarlargo {
            get {
                return ResourceManager.GetString("Sumarlargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla.
        /// </summary>
        public static string Tabla {
            get {
                return ResourceManager.GetString("Tabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo oficina.
        /// </summary>
        public static string Tiempooficinatecnica {
            get {
                return ResourceManager.GetString("Tiempooficinatecnica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoconsumo.
        /// </summary>
        public static string TipoAlbaranAutocomsumo {
            get {
                return ResourceManager.GetString("TipoAlbaranAutocomsumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devolución.
        /// </summary>
        public static string TipoAlbaranDevolucion {
            get {
                return ResourceManager.GetString("TipoAlbaranDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habitual.
        /// </summary>
        public static string TipoAlbaranHabitual {
            get {
                return ResourceManager.GetString("TipoAlbaranHabitual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reclamación.
        /// </summary>
        public static string TipoAlbaranReclamacion {
            get {
                return ResourceManager.GetString("TipoAlbaranReclamacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de lote.
        /// </summary>
        public static string TipoAlmacenLote {
            get {
                return ResourceManager.GetString("TipoAlmacenLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionado.
        /// </summary>
        public static string TipoAlmacenLoteGestionado {
            get {
                return ResourceManager.GetString("TipoAlmacenLoteGestionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mercadería.
        /// </summary>
        public static string TipoAlmacenLoteMercaderia {
            get {
                return ResourceManager.GetString("TipoAlmacenLoteMercaderia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propio.
        /// </summary>
        public static string TipoAlmacenLotePropio {
            get {
                return ResourceManager.GetString("TipoAlmacenLotePropio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio.
        /// </summary>
        public static string Tipocambio {
            get {
                return ResourceManager.GetString("Tipocambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de coste.
        /// </summary>
        public static string Tipocoste {
            get {
                return ResourceManager.GetString("Tipocoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de documento.
        /// </summary>
        public static string Tipodocumento {
            get {
                return ResourceManager.GetString("Tipodocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación.
        /// </summary>
        public static string Tipooperacion {
            get {
                return ResourceManager.GetString("Tipooperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar recepción de stock.
        /// </summary>
        public static string TipoOperacionServiceActualizar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bundle.
        /// </summary>
        public static string TipoOperacionServiceBundle {
            get {
                return ResourceManager.GetString("TipoOperacionServiceBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar recepción de stock.
        /// </summary>
        public static string TipoOperacionServiceEliminar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar albarán de entrega.
        /// </summary>
        public static string TipoOperacionServiceEntregaActualizar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceEntregaActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar albarán de entrega.
        /// </summary>
        public static string TipoOperacionServiceEntregaEliminar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceEntregaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear albarán de entrega.
        /// </summary>
        public static string TipoOperacionServiceEntregaInsertar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceEntregaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear recepción de stock.
        /// </summary>
        public static string TipoOperacionServiceInsertar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kit.
        /// </summary>
        public static string TipoOperacionServiceKit {
            get {
                return ResourceManager.GetString("TipoOperacionServiceKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimiento de almacén.
        /// </summary>
        public static string TipoOperacionServiceMovimientoAlmacen {
            get {
                return ResourceManager.GetString("TipoOperacionServiceMovimientoAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remedir.
        /// </summary>
        public static string TipoOperacionServiceRemedir {
            get {
                return ResourceManager.GetString("TipoOperacionServiceRemedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar reserva.
        /// </summary>
        public static string TipoOperacionServiceReservaActualizar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceReservaActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar reserva.
        /// </summary>
        public static string TipoOperacionServiceReservaEliminar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceReservaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear reserva.
        /// </summary>
        public static string TipoOperacionServiceReservaInsertar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceReservaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar transformación de pieza.
        /// </summary>
        public static string TipoOperacionServiceTransformacionActualizar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceTransformacionActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar transformación de pieza.
        /// </summary>
        public static string TipoOperacionServiceTransformacionEliminar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceTransformacionEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar transformación de pieza.
        /// </summary>
        public static string TipoOperacionServiceTransformacionInsertar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceTransformacionInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida traspaso almacén.
        /// </summary>
        public static string TipoOperacionServiceTraspasosalmacenActualizar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceTraspasosalmacenActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar traspaso almacén.
        /// </summary>
        public static string TipoOperacionServiceTraspasosalmacenEliminar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceTraspasosalmacenEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar traspaso almacén.
        /// </summary>
        public static string TipoOperacionServiceTraspasosalmacenInsertar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceTraspasosalmacenInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reparto.
        /// </summary>
        public static string Tiporeparto {
            get {
                return ResourceManager.GetString("Tiporeparto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albaranes de taller.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albarán de compra.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad de negocio.
        /// </summary>
        public static string Unidadnegocio {
            get {
                return ResourceManager.GetString("Unidadnegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variable.
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vto. C. Crédito.
        /// </summary>
        public static string Vencimientocartacredito {
            get {
                return ResourceManager.GetString("Vencimientocartacredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En stock.
        /// </summary>
        public static string Vendido {
            get {
                return ResourceManager.GetString("Vendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        public static string Volumen {
            get {
                return ResourceManager.GetString("Volumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona.
        /// </summary>
        public static string Zona {
            get {
                return ResourceManager.GetString("Zona", resourceCulture);
            }
        }
    }
}
