//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Aseguradoras {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Aseguradoras() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Aseguradoras", typeof(Aseguradoras).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancos.
        /// </summary>
        public static string Bancos {
            get {
                return ResourceManager.GetString("Bancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactos.
        /// </summary>
        public static string Contactos {
            get {
                return ResourceManager.GetString("Contactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días impago.
        /// </summary>
        public static string Diasimpago {
            get {
                return ResourceManager.GetString("Diasimpago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días impago Vto. prorrogado.
        /// </summary>
        public static string Diasimpagovencimientoprorrogado {
            get {
                return ResourceManager.GetString("Diasimpagovencimientoprorrogado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direcciones.
        /// </summary>
        public static string Direcciones {
            get {
                return ResourceManager.GetString("Direcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio indicar una Fecha de fin.
        /// </summary>
        public static string ErrorFechaFin {
            get {
                return ResourceManager.GetString("ErrorFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio indicar una Fecha de inicio.
        /// </summary>
        public static string ErrorFechaInicio {
            get {
                return ResourceManager.GetString("ErrorFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha de inicio debe ser menor que la Fecha de fin.
        /// </summary>
        public static string ErrorFechaInicioMayorFechaFin {
            get {
                return ResourceManager.GetString("ErrorFechaInicioMayorFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado el tipo de cuenta para Compañias de seguro.
        /// </summary>
        public static string ErrorTipoCuentaConfiguracion {
            get {
                return ResourceManager.GetString("ErrorTipoCuentaConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de fin.
        /// </summary>
        public static string Fechafin {
            get {
                return ResourceManager.GetString("Fechafin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de inicio.
        /// </summary>
        public static string Fechainicio {
            get {
                return ResourceManager.GetString("Fechainicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string Fkcuentas {
            get {
                return ResourceManager.GetString("Fkcuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de la compañía.
        /// </summary>
        public static string InformacionCompañia {
            get {
                return ResourceManager.GetString("InformacionCompañia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha definido un Tipo de cuenta para las compañías de seguros.
        /// </summary>
        public static string LblMensajeTipoCuenta {
            get {
                return ResourceManager.GetString("LblMensajeTipoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de poliza.
        /// </summary>
        public static string Numeropoliza {
            get {
                return ResourceManager.GetString("Numeropoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de prorrogas.
        /// </summary>
        public static string Numeroprorrogas {
            get {
                return ResourceManager.GetString("Numeroprorrogas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de recibos.
        /// </summary>
        public static string Numerorecibos {
            get {
                return ResourceManager.GetString("Numerorecibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Cobertura riesgo.
        /// </summary>
        public static string Porcentajecoberturariesgo {
            get {
                return ResourceManager.GetString("Porcentajecoberturariesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prima anual.
        /// </summary>
        public static string Primaanual {
            get {
                return ResourceManager.GetString("Primaanual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón social.
        /// </summary>
        public static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañía de seguros.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañía de seguros.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
    }
}
