//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BancosMandatos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BancosMandatos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.BancosMandatos", typeof(BancosMandatos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancos.
        /// </summary>
        public static string Bancos {
            get {
                return ResourceManager.GetString("Bancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BIC.
        /// </summary>
        public static string Bic {
            get {
                return ResourceManager.GetString("Bic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueado.
        /// </summary>
        public static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contador confirming.
        /// </summary>
        public static string Contadorconfirming {
            get {
                return ResourceManager.GetString("Contadorconfirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato confirming.
        /// </summary>
        public static string Contratoconfirmig {
            get {
                return ResourceManager.GetString("Contratoconfirmig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C. Postal.
        /// </summary>
        public static string Cpostal {
            get {
                return ResourceManager.GetString("Cpostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del banco.
        /// </summary>
        public static string DatosBanco {
            get {
                return ResourceManager.GetString("DatosBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Defecto.
        /// </summary>
        public static string Defecto {
            get {
                return ResourceManager.GetString("Defecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devolver a.
        /// </summary>
        public static string Devolvera {
            get {
                return ResourceManager.GetString("Devolvera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esquema.
        /// </summary>
        public static string Esquema {
            get {
                return ResourceManager.GetString("Esquema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de expiración.
        /// </summary>
        public static string Fechaexpiracion {
            get {
                return ResourceManager.GetString("Fechaexpiracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de la firma.
        /// </summary>
        public static string Fechafirma {
            get {
                return ResourceManager.GetString("Fechafirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de la última remesa.
        /// </summary>
        public static string Fechaultimaremesa {
            get {
                return ResourceManager.GetString("Fechaultimaremesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizado.
        /// </summary>
        public static string Finalizado {
            get {
                return ResourceManager.GetString("Finalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string Fkcuentas {
            get {
                return ResourceManager.GetString("Fkcuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string Fkpaises {
            get {
                return ResourceManager.GetString("Fkpaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string Fkprovincias {
            get {
                return ResourceManager.GetString("Fkprovincias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IBAN.
        /// </summary>
        public static string Iban {
            get {
                return ResourceManager.GetString("Iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id. Acreedor.
        /// </summary>
        public static string Idacreedor {
            get {
                return ResourceManager.GetString("Idacreedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id. Mandato.
        /// </summary>
        public static string Idmandato {
            get {
                return ResourceManager.GetString("Idmandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe límite recibo.
        /// </summary>
        public static string Importelimiterecibo {
            get {
                return ResourceManager.GetString("Importelimiterecibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe mandato.
        /// </summary>
        public static string Importemandato {
            get {
                return ResourceManager.GetString("Importemandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe remesados.
        /// </summary>
        public static string Importeremesados {
            get {
                return ResourceManager.GetString("Importeremesados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandatos.
        /// </summary>
        public static string Mandatos {
            get {
                return ResourceManager.GetString("Mandatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Notas {
            get {
                return ResourceManager.GetString("Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona de contacto.
        /// </summary>
        public static string Personacontacto {
            get {
                return ResourceManager.GetString("Personacontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibos mandato.
        /// </summary>
        public static string Recibosmandato {
            get {
                return ResourceManager.GetString("Recibosmandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibos remesados.
        /// </summary>
        public static string Recibosremesados {
            get {
                return ResourceManager.GetString("Recibosremesados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remesas.
        /// </summary>
        public static string Remesas {
            get {
                return ResourceManager.GetString("Remesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Riesgo extranjero.
        /// </summary>
        public static string Riesgoextranjero {
            get {
                return ResourceManager.GetString("Riesgoextranjero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Riesgo nacional.
        /// </summary>
        public static string Riesgonacional {
            get {
                return ResourceManager.GetString("Riesgonacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sufijo acreedor.
        /// </summary>
        public static string Sufijoacreedor {
            get {
                return ResourceManager.GetString("Sufijoacreedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono banco.
        /// </summary>
        public static string Telefonobanco {
            get {
                return ResourceManager.GetString("Telefonobanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de adeudo.
        /// </summary>
        public static string Tipoadeudo {
            get {
                return ResourceManager.GetString("Tipoadeudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adeudo recurrente.
        /// </summary>
        public static string TipoAdeudoAdeudoRecurrente {
            get {
                return ResourceManager.GetString("TipoAdeudoAdeudoRecurrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer adeudo recurrente.
        /// </summary>
        public static string TipoAdeudoPrimerAdeudoRecurrente {
            get {
                return ResourceManager.GetString("TipoAdeudoPrimerAdeudoRecurrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último adeudo recurrente.
        /// </summary>
        public static string TipoAdeudoUltimoAdeudoRecurrente {
            get {
                return ResourceManager.GetString("TipoAdeudoUltimoAdeudoRecurrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Único.
        /// </summary>
        public static string TipoAdeudoUnico {
            get {
                return ResourceManager.GetString("TipoAdeudoUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandato.
        /// </summary>
        public static string TipoBancosMandatosMandato {
            get {
                return ResourceManager.GetString("TipoBancosMandatosMandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string TiposBancosMandatosBanco {
            get {
                return ResourceManager.GetString("TiposBancosMandatosBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secuencia SEPA.
        /// </summary>
        public static string Tiposecuenciasepa {
            get {
                return ResourceManager.GetString("Tiposecuenciasepa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periódico.
        /// </summary>
        public static string TipoSecuenciaSepaPeriodico {
            get {
                return ResourceManager.GetString("TipoSecuenciaSepaPeriodico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Único.
        /// </summary>
        public static string TipoSecuenciaSepaUnico {
            get {
                return ResourceManager.GetString("TipoSecuenciaSepaUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancos y mandatos.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
