//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Contadores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contadores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Contadores", typeof(Contadores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar el contador porque está asignado a una Serie de documento.
        /// </summary>
        public static string ErrorContadorSerieUtilizada {
            get {
                return ResourceManager.GetString("ErrorContadorSerieUtilizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio especificar una configuración para el contador.
        /// </summary>
        public static string ErrorLineaObligatoria {
            get {
                return ResourceManager.GetString("ErrorLineaObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud máxima del contador es de 12 caracteres.
        /// </summary>
        public static string ErrorLongitudMaximaLineas {
            get {
                return ResourceManager.GetString("ErrorLongitudMaximaLineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si el contador se inicializa cada año es obligatorio indicar el segmento del año.
        /// </summary>
        public static string ErrorSegmentoAñoObligatorio {
            get {
                return ResourceManager.GetString("ErrorSegmentoAñoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si el contador se inicializa cada mes es obligatorio indicar el segmento del mes.
        /// </summary>
        public static string ErrorSegmentoMesObligatorio {
            get {
                return ResourceManager.GetString("ErrorSegmentoMesObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio indicar el segmento identificador del contador.
        /// </summary>
        public static string ErrorSegmentoObligatorio {
            get {
                return ResourceManager.GetString("ErrorSegmentoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud.
        /// </summary>
        public static string Longitud {
            get {
                return ResourceManager.GetString("Longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor primer documento.
        /// </summary>
        public static string Primerdocumento {
            get {
                return ResourceManager.GetString("Primerdocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tipocontador {
            get {
                return ResourceManager.GetString("Tipocontador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multidocumento.
        /// </summary>
        public static string TipoContadorMultidocumento {
            get {
                return ResourceManager.GetString("TipoContadorMultidocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privado.
        /// </summary>
        public static string TipoContadorPrivado {
            get {
                return ResourceManager.GetString("TipoContadorPrivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel de re inicialización.
        /// </summary>
        public static string Tipoinicio {
            get {
                return ResourceManager.GetString("Tipoinicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anual.
        /// </summary>
        public static string TipoInicioAnual {
            get {
                return ResourceManager.GetString("TipoInicioAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensual.
        /// </summary>
        public static string TipoInicioMensual {
            get {
                return ResourceManager.GetString("TipoInicioMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semanal.
        /// </summary>
        public static string TipoInicioSemanal {
            get {
                return ResourceManager.GetString("TipoInicioSemanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin reinicio.
        /// </summary>
        public static string TipoInicioSinreinicio {
            get {
                return ResourceManager.GetString("TipoInicioSinreinicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de segmento.
        /// </summary>
        public static string Tiposegmento {
            get {
                return ResourceManager.GetString("Tiposegmento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string TiposSegmentosAño {
            get {
                return ResourceManager.GetString("TiposSegmentosAño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constante.
        /// </summary>
        public static string TiposSegmentosConstante {
            get {
                return ResourceManager.GetString("TiposSegmentosConstante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        public static string TiposSegmentosMes {
            get {
                return ResourceManager.GetString("TiposSegmentosMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secuencia.
        /// </summary>
        public static string TiposSegmentosSecuencia {
            get {
                return ResourceManager.GetString("TiposSegmentosSecuencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semana.
        /// </summary>
        public static string TiposSegmentosSemana {
            get {
                return ResourceManager.GetString("TiposSegmentosSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie.
        /// </summary>
        public static string TiposSegmentosSerie {
            get {
                return ResourceManager.GetString("TiposSegmentosSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contadores.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
    }
}
