//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ejercicios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ejercicios() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Ejercicios", typeof(Ejercicios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contabilidad cerrada hasta.
        /// </summary>
        public static string Contabilidadcerradahasta {
            get {
                return ResourceManager.GetString("Contabilidadcerradahasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterio de IVA.
        /// </summary>
        public static string Criterioiva {
            get {
                return ResourceManager.GetString("Criterioiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción corta.
        /// </summary>
        public static string Descripcioncorta {
            get {
                return ResourceManager.GetString("Descripcioncorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        public static string Desde {
            get {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abierto.
        /// </summary>
        public static string EstadoEjercicioAbierto {
            get {
                return ResourceManager.GetString("EstadoEjercicioAbierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado.
        /// </summary>
        public static string EstadoEjercicioCerrado {
            get {
                return ResourceManager.GetString("EstadoEjercicioCerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regularización Existencias.
        /// </summary>
        public static string EstadoEjercicioExistencias {
            get {
                return ResourceManager.GetString("EstadoEjercicioExistencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regularización Grupos 6 y 7.
        /// </summary>
        public static string EstadoEjercicioGrupos {
            get {
                return ResourceManager.GetString("EstadoEjercicioGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejercicio anterior.
        /// </summary>
        public static string Fkejercicios {
            get {
                return ResourceManager.GetString("Fkejercicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie contable.
        /// </summary>
        public static string FkseriescontablesAST {
            get {
                return ResourceManager.GetString("FkseriescontablesAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cartera cobros.
        /// </summary>
        public static string FkseriescontablesCRC {
            get {
                return ResourceManager.GetString("FkseriescontablesCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cartera pagos.
        /// </summary>
        public static string FkseriescontablesCRP {
            get {
                return ResourceManager.GetString("FkseriescontablesCRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inmovilizado.
        /// </summary>
        public static string FkseriescontablesINM {
            get {
                return ResourceManager.GetString("FkseriescontablesINM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iva repercutido.
        /// </summary>
        public static string FkseriescontablesIVP {
            get {
                return ResourceManager.GetString("FkseriescontablesIVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iva soportado.
        /// </summary>
        public static string FkseriescontablesIVS {
            get {
                return ResourceManager.GetString("FkseriescontablesIVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsión cobros.
        /// </summary>
        public static string FkseriescontablesPRC {
            get {
                return ResourceManager.GetString("FkseriescontablesPRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsión pagos.
        /// </summary>
        public static string FkseriescontablesPRP {
            get {
                return ResourceManager.GetString("FkseriescontablesPRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión remesas.
        /// </summary>
        public static string FkseriescontablesREM {
            get {
                return ResourceManager.GetString("FkseriescontablesREM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión.
        /// </summary>
        public static string Gestion {
            get {
                return ResourceManager.GetString("Gestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        public static string Hasta {
            get {
                return ResourceManager.GetString("Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA cerrado hasta.
        /// </summary>
        public static string Registroivacerradohasta {
            get {
                return ResourceManager.GetString("Registroivacerradohasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejercicios.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
