//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Familiasproductos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Familiasproductos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Familiasproductos", typeof(Familiasproductos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es artículo de negocio.
        /// </summary>
        public static string Articulonegocio {
            get {
                return ResourceManager.GetString("Articulonegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasificación de artículo.
        /// </summary>
        public static string Clasificacion {
            get {
                return ResourceManager.GetString("Clasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumibles.
        /// </summary>
        public static string Consumibles {
            get {
                return ResourceManager.GetString("Consumibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generación descripción.
        /// </summary>
        public static string Descripcion1generada {
            get {
                return ResourceManager.GetString("Descripcion1generada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generación descripción secundaria.
        /// </summary>
        public static string Descripcion2generada {
            get {
                return ResourceManager.GetString("Descripcion2generada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción corta.
        /// </summary>
        public static string Descripcionabreviada {
            get {
                return ResourceManager.GetString("Descripcionabreviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generación descripción abreviada.
        /// </summary>
        public static string Descripcionabreviadagenerada {
            get {
                return ResourceManager.GetString("Descripcionabreviadagenerada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir descripción acabado.
        /// </summary>
        public static string Descripcionarticuloacabado {
            get {
                return ResourceManager.GetString("Descripcionarticuloacabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir descripción característica.
        /// </summary>
        public static string Descripcionarticulocaracteristica {
            get {
                return ResourceManager.GetString("Descripcionarticulocaracteristica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir descripción familia material.
        /// </summary>
        public static string Descripcionarticulofamiliamaterial {
            get {
                return ResourceManager.GetString("Descripcionarticulofamiliamaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir descripción grosor.
        /// </summary>
        public static string Descripcionarticulogrosor {
            get {
                return ResourceManager.GetString("Descripcionarticulogrosor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir descripción material.
        /// </summary>
        public static string Descripcionarticulomaterial {
            get {
                return ResourceManager.GetString("Descripcionarticulomaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir descripción familia.
        /// </summary>
        public static string Descripionarticulofamilia {
            get {
                return ResourceManager.GetString("Descripionarticulofamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite editar ancho.
        /// </summary>
        public static string Editarancho {
            get {
                return ResourceManager.GetString("Editarancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite editar grueso.
        /// </summary>
        public static string Editargrueso {
            get {
                return ResourceManager.GetString("Editargrueso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite editar largo.
        /// </summary>
        public static string Editarlargo {
            get {
                return ResourceManager.GetString("Editarlargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor ancho del articulo {0} debe estar entre {1} y {2}.
        /// </summary>
        public static string ErrorAncho {
            get {
                return ResourceManager.GetString("ErrorAncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede asignar un contador a una familia que no tiene gestión de stock/lote.
        /// </summary>
        public static string ErrorContadorGestionStock {
            get {
                return ResourceManager.GetString("ErrorContadorGestionStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor grueso del articulo {0} debe estar entre {1} y {2}.
        /// </summary>
        public static string ErrorGrueso {
            get {
                return ResourceManager.GetString("ErrorGrueso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor largo del articulo {0} debe estar entre {1} y {2}.
        /// </summary>
        public static string ErrorLargo {
            get {
                return ResourceManager.GetString("ErrorLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contador.
        /// </summary>
        public static string Fkcontador {
            get {
                return ResourceManager.GetString("Fkcontador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo IVA.
        /// </summary>
        public static string Fkgruposiva {
            get {
                return ResourceManager.GetString("Fkgruposiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guía contable.
        /// </summary>
        public static string Fkguiascontables {
            get {
                return ResourceManager.GetString("Fkguiascontables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades de medida.
        /// </summary>
        public static string Fkunidadesmedida {
            get {
                return ResourceManager.GetString("Fkunidadesmedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de stock.
        /// </summary>
        public static string Gestionstock {
            get {
                return ResourceManager.GetString("Gestionstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho máximo.
        /// </summary>
        public static string MaxAncho {
            get {
                return ResourceManager.GetString("MaxAncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grueso máximo.
        /// </summary>
        public static string MaxGrueso {
            get {
                return ResourceManager.GetString("MaxGrueso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Largo máximo.
        /// </summary>
        public static string MaxLargo {
            get {
                return ResourceManager.GetString("MaxLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho mínimo.
        /// </summary>
        public static string MinAncho {
            get {
                return ResourceManager.GetString("MinAncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grueso mínimo.
        /// </summary>
        public static string MinGrueso {
            get {
                return ResourceManager.GetString("MinGrueso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Largo mínimo.
        /// </summary>
        public static string MinLargo {
            get {
                return ResourceManager.GetString("MinLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acabado.
        /// </summary>
        public static string PartesDescripcionAcabado {
            get {
                return ResourceManager.GetString("PartesDescripcionAcabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Características.
        /// </summary>
        public static string PartesDescripcionCaracteristica {
            get {
                return ResourceManager.GetString("PartesDescripcionCaracteristica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia.
        /// </summary>
        public static string PartesDescripcionFamilia {
            get {
                return ResourceManager.GetString("PartesDescripcionFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia material.
        /// </summary>
        public static string PartesDescripcionFamiliamaterial {
            get {
                return ResourceManager.GetString("PartesDescripcionFamiliamaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosor.
        /// </summary>
        public static string PartesDescripcionGrosor {
            get {
                return ResourceManager.GetString("PartesDescripcionGrosor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material.
        /// </summary>
        public static string PartesDescripcionMaterial {
            get {
                return ResourceManager.GetString("PartesDescripcionMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo familia.
        /// </summary>
        public static string Tipofamilia {
            get {
                return ResourceManager.GetString("Tipofamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloque.
        /// </summary>
        public static string TipoFamiliaBloque {
            get {
                return ResourceManager.GetString("TipoFamiliaBloque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string TipoFamiliaGeneral {
            get {
                return ResourceManager.GetString("TipoFamiliaGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla.
        /// </summary>
        public static string TipoFamiliaTabla {
            get {
                return ResourceManager.GetString("TipoFamiliaTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libre.
        /// </summary>
        public static string TipoLibreTabla {
            get {
                return ResourceManager.GetString("TipoLibreTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias de productos.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar acabado.
        /// </summary>
        public static string Validaracabado {
            get {
                return ResourceManager.GetString("Validaracabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar característica.
        /// </summary>
        public static string Validarcaracteristica {
            get {
                return ResourceManager.GetString("Validarcaracteristica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar dimensiones.
        /// </summary>
        public static string ValidarDimensiones {
            get {
                return ResourceManager.GetString("ValidarDimensiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar grosor.
        /// </summary>
        public static string Validargrosor {
            get {
                return ResourceManager.GetString("Validargrosor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar material.
        /// </summary>
        public static string Validarmaterial {
            get {
                return ResourceManager.GetString("Validarmaterial", resourceCulture);
            }
        }
    }
}
