//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Formaspago {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Formaspago() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Formaspago", typeof(Formaspago).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días de vencimiento.
        /// </summary>
        public static string DiasVencimiento {
            get {
                return ResourceManager.GetString("DiasVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editable.
        /// </summary>
        public static string Editable {
            get {
                return ResourceManager.GetString("Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En caso de indicar porcentajes en los vencimientos, su suma total debe ser el 100%.
        /// </summary>
        public static string ErrorSumaPorcentajes {
            get {
                return ResourceManager.GetString("ErrorSumaPorcentajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excluir vencimientos en festivos.
        /// </summary>
        public static string ExcluirFestivos {
            get {
                return ResourceManager.GetString("ExcluirFestivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string FkGruposformaspago {
            get {
                return ResourceManager.GetString("FkGruposformaspago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir vencimientos en las facturas.
        /// </summary>
        public static string ImprimirVencimientoFacturas {
            get {
                return ResourceManager.GetString("ImprimirVencimientoFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instruccion.
        /// </summary>
        public static string Instruccion {
            get {
                return ResourceManager.GetString("Instruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modos de pago.
        /// </summary>
        public static string ModoPago {
            get {
                return ResourceManager.GetString("ModoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre2 {
            get {
                return ResourceManager.GetString("Nombre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje de pago.
        /// </summary>
        public static string PorcentajePago {
            get {
                return ResourceManager.GetString("PorcentajePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recargo financiero sobre la comisión.
        /// </summary>
        public static string RecargoFinanciero {
            get {
                return ResourceManager.GetString("RecargoFinanciero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remesa.
        /// </summary>
        public static string Remesa {
            get {
                return ResourceManager.GetString("Remesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Riesgo.
        /// </summary>
        public static string Riesgo {
            get {
                return ResourceManager.GetString("Riesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formas de pago.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de pago.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor inicial.
        /// </summary>
        public static string Valorinicial {
            get {
                return ResourceManager.GetString("Valorinicial", resourceCulture);
            }
        }
    }
}
