//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Grosores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Grosores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Grosores", typeof(Grosores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente corte telar.
        /// </summary>
        public static string Coeficientetelares {
            get {
                return ResourceManager.GetString("Coeficientetelares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente corte bloques.
        /// </summary>
        public static string Coficientecortabloques {
            get {
                return ResourceManager.GetString("Coficientecortabloques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción abreviada.
        /// </summary>
        public static string Descripcionabreviada {
            get {
                return ResourceManager.GetString("Descripcionabreviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosor (m).
        /// </summary>
        public static string Grosor {
            get {
                return ResourceManager.GetString("Grosor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a para un espesor de disco  de &lt;strong&gt;{0}&lt;/strong&gt; cm.
        /// </summary>
        public static string LblParaEspesorDisco {
            get {
                return ResourceManager.GetString("LblParaEspesorDisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a para un espesor de fleje de &lt;strong&gt;{0}&lt;/strong&gt; cm.
        /// </summary>
        public static string LblParaEspesorFleje {
            get {
                return ResourceManager.GetString("LblParaEspesorFleje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string TipoFormatoGrosorCodigo {
            get {
                return ResourceManager.GetString("TipoFormatoGrosorCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código + unidad.
        /// </summary>
        public static string TipoFormatoGrosorCodigoyUnidad {
            get {
                return ResourceManager.GetString("TipoFormatoGrosorCodigoyUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosor en cm.
        /// </summary>
        public static string TipoFormatoGrosorGrosorcm {
            get {
                return ResourceManager.GetString("TipoFormatoGrosorGrosorcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosor en cm + unidad.
        /// </summary>
        public static string TipoFormatoGrosorGrosorcmyUnidad {
            get {
                return ResourceManager.GetString("TipoFormatoGrosorGrosorcmyUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosor en m.
        /// </summary>
        public static string TipoFormatoGrosorGrosorm {
            get {
                return ResourceManager.GetString("TipoFormatoGrosorGrosorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosor en m + unidad.
        /// </summary>
        public static string TipoFormatoGrosorGrosormyUnidad {
            get {
                return ResourceManager.GetString("TipoFormatoGrosorGrosormyUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosores.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
