//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStockSeguridad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStockSeguridad() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.LogStockSeguridad", typeof(LogStockSeguridad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacén.
        /// </summary>
        public static string Almacen {
            get {
                return ResourceManager.GetString("Almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UD.
        /// </summary>
        public static string Codigounidad {
            get {
                return ResourceManager.GetString("Codigounidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Doc..
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido óptimo.
        /// </summary>
        public static string Pedidooptimo {
            get {
                return ResourceManager.GetString("Pedidooptimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        public static string Stockactual {
            get {
                return ResourceManager.GetString("Stockactual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log rotura del stock de seguridad.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
