//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Operarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Operarios() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Operarios", typeof(Operarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de alta.
        /// </summary>
        public static string Fechaalta {
            get {
                return ResourceManager.GetString("Fechaalta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de ingreso.
        /// </summary>
        public static string Fechaingreso {
            get {
                return ResourceManager.GetString("Fechaingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string Fechanacimiento {
            get {
                return ResourceManager.GetString("Fechanacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo en la empresa.
        /// </summary>
        public static string Fkcargo {
            get {
                return ResourceManager.GetString("Fkcargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo contrato.
        /// </summary>
        public static string Fkcontratoactual {
            get {
                return ResourceManager.GetString("Fkcontratoactual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string Fkcuentas {
            get {
                return ResourceManager.GetString("Fkcuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cta. Tesorería.
        /// </summary>
        public static string Fkcuentatesoreria {
            get {
                return ResourceManager.GetString("Fkcuentatesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado civil.
        /// </summary>
        public static string Fkestadocivil {
            get {
                return ResourceManager.GetString("Fkestadocivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha definido un Tipo de cuenta para los operarios..
        /// </summary>
        public static string LblMensajeTipoCuenta {
            get {
                return ResourceManager.GetString("LblMensajeTipoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nif.
        /// </summary>
        public static string Nif {
            get {
                return ResourceManager.GetString("Nif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas: .
        /// </summary>
        public static string Notas {
            get {
                return ResourceManager.GetString("Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de hijos.
        /// </summary>
        public static string Numerohijos {
            get {
                return ResourceManager.GetString("Numerohijos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº seguridad social.
        /// </summary>
        public static string Numeroseguridadsocial {
            get {
                return ResourceManager.GetString("Numeroseguridadsocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Población.
        /// </summary>
        public static string Poblacion {
            get {
                return ResourceManager.GetString("Poblacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón social.
        /// </summary>
        public static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talla Calzado.
        /// </summary>
        public static string Tallacalzado {
            get {
                return ResourceManager.GetString("Tallacalzado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talla Camisa.
        /// </summary>
        public static string Tallacamisa {
            get {
                return ResourceManager.GetString("Tallacamisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talla Pantalon.
        /// </summary>
        public static string Tallapantalon {
            get {
                return ResourceManager.GetString("Tallapantalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operarios.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operario.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enfermedad/Accidente Ult. Fecha de Alta.
        /// </summary>
        public static string Ultimafechaalta {
            get {
                return ResourceManager.GetString("Ultimafechaalta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enfermedad/Accidente Ult.Fecha de Baja.
        /// </summary>
        public static string Ultimafechabaja {
            get {
                return ResourceManager.GetString("Ultimafechabaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de vencimiento.
        /// </summary>
        public static string Vencimientocontrato {
            get {
                return ResourceManager.GetString("Vencimientocontrato", resourceCulture);
            }
        }
    }
}
