//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeticionesAsincronas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeticionesAsincronas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.PeticionesAsincronas", typeof(PeticionesAsincronas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peticion completada sin errores.
        /// </summary>
        public static string Correcto {
            get {
                return ResourceManager.GetString("Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso se encuentra en ejecución.
        /// </summary>
        public static string EnEjecucion {
            get {
                return ResourceManager.GetString("EnEjecucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido algún erorr, a continuación se muestra el log de errores.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha detenido la ejecución debido a la siguiente excepción.
        /// </summary>
        public static string ErrorCritico {
            get {
                return ResourceManager.GetString("ErrorCritico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En curso.
        /// </summary>
        public static string EstadoPeticionEnCurso {
            get {
                return ResourceManager.GetString("EstadoPeticionEnCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string EstadoPeticionError {
            get {
                return ResourceManager.GetString("EstadoPeticionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizada.
        /// </summary>
        public static string EstadoPeticionFinalizada {
            get {
                return ResourceManager.GetString("EstadoPeticionFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizada con errores.
        /// </summary>
        public static string EstadoPeticionFinalizadaLogs {
            get {
                return ResourceManager.GetString("EstadoPeticionFinalizadaLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado de la ejecución:.
        /// </summary>
        public static string Resultado {
            get {
                return ResourceManager.GetString("Resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar Acreedores.
        /// </summary>
        public static string TipoImportacionImportarAcreedores {
            get {
                return ResourceManager.GetString("TipoImportacionImportarAcreedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar artículos.
        /// </summary>
        public static string TipoImportacionImportarArticulos {
            get {
                return ResourceManager.GetString("TipoImportacionImportarArticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar Clientes.
        /// </summary>
        public static string TipoImportacionImportarClientes {
            get {
                return ResourceManager.GetString("TipoImportacionImportarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar asientos.
        /// </summary>
        public static string TipoImportacionImportarMovs {
            get {
                return ResourceManager.GetString("TipoImportacionImportarMovs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar Proveedores.
        /// </summary>
        public static string TipoImportacionImportarProveedores {
            get {
                return ResourceManager.GetString("TipoImportacionImportarProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar stock.
        /// </summary>
        public static string TipoImportacionImportarStock {
            get {
                return ResourceManager.GetString("TipoImportacionImportarStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cálculo.
        /// </summary>
        public static string TipoPeticionCalculo {
            get {
                return ResourceManager.GetString("TipoPeticionCalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importación.
        /// </summary>
        public static string TipoPeticionImportacion {
            get {
                return ResourceManager.GetString("TipoPeticionImportacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peticiones Asíncronas.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
