//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistroIvaRepercutido {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistroIvaRepercutido() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.RegistroIvaRepercutido", typeof(RegistroIvaRepercutido).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptada.
        /// </summary>
        public static string Aceptada {
            get {
                return ResourceManager.GetString("Aceptada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta.
        /// </summary>
        public static string Alta {
            get {
                return ResourceManager.GetString("Alta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base retención.
        /// </summary>
        public static string Baseretencion {
            get {
                return ResourceManager.GetString("Baseretencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bien de inversión.
        /// </summary>
        public static string Bieninversion {
            get {
                return ResourceManager.GetString("Bieninversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caja.
        /// </summary>
        public static string Caja {
            get {
                return ResourceManager.GetString("Caja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código País.
        /// </summary>
        public static string Codigopais {
            get {
                return ResourceManager.GetString("Codigopais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contabilizar como cobrado/pagado.
        /// </summary>
        public static string Contabilizar {
            get {
                return ResourceManager.GetString("Contabilizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterio de IVA factura original.
        /// </summary>
        public static string Criterioivafactoriginal {
            get {
                return ResourceManager.GetString("Criterioivafactoriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterio de IVA.
        /// </summary>
        public static string Criterioivafactura {
            get {
                return ResourceManager.GetString("Criterioivafactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterio de IVA.
        /// </summary>
        public static string Criterioivageneral {
            get {
                return ResourceManager.GetString("Criterioivageneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CSV.
        /// </summary>
        public static string Csv {
            get {
                return ResourceManager.GetString("Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta cliente/acreedor.
        /// </summary>
        public static string Cuentacliente {
            get {
                return ResourceManager.GetString("Cuentacliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta Cliente.
        /// </summary>
        public static string Cuentaclientecontraparte {
            get {
                return ResourceManager.GetString("Cuentaclientecontraparte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta ventas/servicios.
        /// </summary>
        public static string Cuentaventas {
            get {
                return ResourceManager.GetString("Cuentaventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción error.
        /// </summary>
        public static string Descripcionerror {
            get {
                return ResourceManager.GetString("Descripcionerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devengo.
        /// </summary>
        public static string Devengo {
            get {
                return ResourceManager.GetString("Devengo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificación de errores registrales.
        /// </summary>
        public static string Errores {
            get {
                return ResourceManager.GetString("Errores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura.
        /// </summary>
        public static string Factura {
            get {
                return ResourceManager.GetString("Factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura rectificativa.
        /// </summary>
        public static string Facturarectificativa {
            get {
                return ResourceManager.GetString("Facturarectificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Alta.
        /// </summary>
        public static string Fechaalta {
            get {
                return ResourceManager.GetString("Fechaalta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de factura.
        /// </summary>
        public static string Fechafactura {
            get {
                return ResourceManager.GetString("Fechafactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha factura original.
        /// </summary>
        public static string Fechafacturaoriginal {
            get {
                return ResourceManager.GetString("Fechafacturaoriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de operacion.
        /// </summary>
        public static string Fechaoperacion {
            get {
                return ResourceManager.GetString("Fechaoperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de registro.
        /// </summary>
        public static string Fecharegistro {
            get {
                return ResourceManager.GetString("Fecharegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cta. Tesorería.
        /// </summary>
        public static string Fkcuentastesoreria {
            get {
                return ResourceManager.GetString("Fkcuentastesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimen de IVA.
        /// </summary>
        public static string Fkregimeniva {
            get {
                return ResourceManager.GetString("Fkregimeniva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retenciones (Tipo).
        /// </summary>
        public static string Fktiporetencion {
            get {
                return ResourceManager.GetString("Fktiporetencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string Identificacion {
            get {
                return ResourceManager.GetString("Identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe retención.
        /// </summary>
        public static string Importeretencion {
            get {
                return ResourceManager.GetString("Importeretencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inmueble.
        /// </summary>
        public static string Inmueble {
            get {
                return ResourceManager.GetString("Inmueble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA.
        /// </summary>
        public static string IVA {
            get {
                return ResourceManager.GetString("IVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo restificación.
        /// </summary>
        public static string Motivorectificacion {
            get {
                return ResourceManager.GetString("Motivorectificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIF.
        /// </summary>
        public static string Nif {
            get {
                return ResourceManager.GetString("Nif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nif Contraparte de la operación.
        /// </summary>
        public static string Nifcontraparte {
            get {
                return ResourceManager.GetString("Nifcontraparte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre o Razón Social Contraparte.
        /// </summary>
        public static string Nombrecontraparte {
            get {
                return ResourceManager.GetString("Nombrecontraparte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num. factura cliente.
        /// </summary>
        public static string Numfacturacliente {
            get {
                return ResourceManager.GetString("Numfacturacliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectifica a la factura Nº.
        /// </summary>
        public static string Numfacturarectificar {
            get {
                return ResourceManager.GetString("Numfacturarectificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operaciones excluidas de la B.I..
        /// </summary>
        public static string Operacionesexluidasbi {
            get {
                return ResourceManager.GetString("Operacionesexluidasbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen documento.
        /// </summary>
        public static string Origendoc {
            get {
                return ResourceManager.GetString("Origendoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        public static string Otro {
            get {
                return ResourceManager.GetString("Otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente.
        /// </summary>
        public static string Pendiente {
            get {
                return ResourceManager.GetString("Pendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo.
        /// </summary>
        public static string Periodo {
            get {
                return ResourceManager.GetString("Periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Retención.
        /// </summary>
        public static string Porcentajeretencion {
            get {
                return ResourceManager.GetString("Porcentajeretencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazada.
        /// </summary>
        public static string Rechazada {
            get {
                return ResourceManager.GetString("Rechazada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Envío / Comunicación.
        /// </summary>
        public static string Tipoenvio {
            get {
                return ResourceManager.GetString("Tipoenvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo factura IVA.
        /// </summary>
        public static string Tipofactura {
            get {
                return ResourceManager.GetString("Tipofactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de identificación.
        /// </summary>
        public static string Tipoidentificacion {
            get {
                return ResourceManager.GetString("Tipoidentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de identificación.
        /// </summary>
        public static string Tipoidentificacionotro {
            get {
                return ResourceManager.GetString("Tipoidentificacionotro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de IVA repercutido.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total factura.
        /// </summary>
        public static string Totalfactura {
            get {
                return ResourceManager.GetString("Totalfactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Varios Destinatarios.
        /// </summary>
        public static string Variosdestinatarios {
            get {
                return ResourceManager.GetString("Variosdestinatarios", resourceCulture);
            }
        }
    }
}
