//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Seguimientos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Seguimientos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Seguimientos", typeof(Seguimientos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string Accion {
            get {
                return ResourceManager.GetString("Accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        public static string Asunto {
            get {
                return ResourceManager.GetString("Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado.
        /// </summary>
        public static string Cerrado {
            get {
                return ResourceManager.GetString("Cerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave coste.
        /// </summary>
        public static string Clavecoste {
            get {
                return ResourceManager.GetString("Clavecoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste.
        /// </summary>
        public static string Coste {
            get {
                return ResourceManager.GetString("Coste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tercero.
        /// </summary>
        public static string Descripciontercero {
            get {
                return ResourceManager.GetString("Descripciontercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento relacionado.
        /// </summary>
        public static string Documentorelacionado {
            get {
                return ResourceManager.GetString("Documentorelacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etapa.
        /// </summary>
        public static string Etapa {
            get {
                return ResourceManager.GetString("Etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Fechadocumento {
            get {
                return ResourceManager.GetString("Fechadocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha próximo seguimiento.
        /// </summary>
        public static string Fechaproximoseguimiento {
            get {
                return ResourceManager.GetString("Fechaproximoseguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha resolución.
        /// </summary>
        public static string Fecharesolucion {
            get {
                return ResourceManager.GetString("Fecharesolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión.
        /// </summary>
        public static string Gestion {
            get {
                return ResourceManager.GetString("Gestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar documento relacionado.
        /// </summary>
        public static string LblBuscarDocumentoRelacionado {
            get {
                return ResourceManager.GetString("LblBuscarDocumentoRelacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen decisión.
        /// </summary>
        public static string Margen {
            get {
                return ResourceManager.GetString("Margen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas.
        /// </summary>
        public static string Notas {
            get {
                return ResourceManager.GetString("Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operario.
        /// </summary>
        public static string Operario {
            get {
                return ResourceManager.GetString("Operario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen.
        /// </summary>
        public static string Origen {
            get {
                return ResourceManager.GetString("Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reacción.
        /// </summary>
        public static string Reaccion {
            get {
                return ResourceManager.GetString("Reaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de doc. relacionado.
        /// </summary>
        public static string Tipodocumentorelacionado {
            get {
                return ResourceManager.GetString("Tipodocumentorelacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimientos.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
