//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Series {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Series() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Series", typeof(Series).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueo.
        /// </summary>
        public static string Bloqueo {
            get {
                return ResourceManager.GetString("Bloqueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie Borrador.
        /// </summary>
        public static string Borrador {
            get {
                return ResourceManager.GetString("Borrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entradas Varias.
        /// </summary>
        public static string EntradasVarias {
            get {
                return ResourceManager.GetString("EntradasVarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede guardar el registro porque la serie esta utilizando un contador de tipo privado que ya está asignado a otra serie..
        /// </summary>
        public static string ErrorContadorPridado {
            get {
                return ResourceManager.GetString("ErrorContadorPridado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar el contador de la serie porque ya ha sido utilizada..
        /// </summary>
        public static string ErrorSerieYaUtilizada {
            get {
                return ResourceManager.GetString("ErrorSerieYaUtilizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es exento IVA.
        /// </summary>
        public static string Exentoiva {
            get {
                return ResourceManager.GetString("Exentoiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contador.
        /// </summary>
        public static string Fkcontadores {
            get {
                return ResourceManager.GetString("Fkcontadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejercicio.
        /// </summary>
        public static string Fkejercicios {
            get {
                return ResourceManager.GetString("Fkejercicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de usuarios.
        /// </summary>
        public static string Fkgruposusuarios {
            get {
                return ResourceManager.GetString("Fkgruposusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monedas.
        /// </summary>
        public static string Fkmonedas {
            get {
                return ResourceManager.GetString("Fkmonedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimen IVA.
        /// </summary>
        public static string Fkregimeniva {
            get {
                return ResourceManager.GetString("Fkregimeniva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie asociada.
        /// </summary>
        public static string Fkseriesasociada {
            get {
                return ResourceManager.GetString("Fkseriesasociada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie rectificativa.
        /// </summary>
        public static string Rectificativa {
            get {
                return ResourceManager.GetString("Rectificativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se incluye en Riesgo.
        /// </summary>
        public static string Riesgo {
            get {
                return ResourceManager.GetString("Riesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salidas Varias.
        /// </summary>
        public static string SalidasVarias {
            get {
                return ResourceManager.GetString("SalidasVarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Lote.
        /// </summary>
        public static string TipoAlmacenLote {
            get {
                return ResourceManager.GetString("TipoAlmacenLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de documento.
        /// </summary>
        public static string Tipodocumento {
            get {
                return ResourceManager.GetString("Tipodocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albaranes de compra.
        /// </summary>
        public static string TipoDocumentosAlbaranesCompra {
            get {
                return ResourceManager.GetString("TipoDocumentosAlbaranesCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albaranes de ventas.
        /// </summary>
        public static string TipoDocumentosAlbaranesVentas {
            get {
                return ResourceManager.GetString("TipoDocumentosAlbaranesVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apuntes de almancén.
        /// </summary>
        public static string TipoDocumentosApuntesAlmacen {
            get {
                return ResourceManager.GetString("TipoDocumentosApuntesAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas de compra.
        /// </summary>
        public static string TipoDocumentosFacturasCompra {
            get {
                return ResourceManager.GetString("TipoDocumentosFacturasCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas de ventas.
        /// </summary>
        public static string TipoDocumentosFacturasVentas {
            get {
                return ResourceManager.GetString("TipoDocumentosFacturasVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos de compra.
        /// </summary>
        public static string TipoDocumentosPedidosCompra {
            get {
                return ResourceManager.GetString("TipoDocumentosPedidosCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos de ventas.
        /// </summary>
        public static string TipoDocumentosPedidosVentas {
            get {
                return ResourceManager.GetString("TipoDocumentosPedidosVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestos de compra.
        /// </summary>
        public static string TipoDocumentosPresupuestosCompra {
            get {
                return ResourceManager.GetString("TipoDocumentosPresupuestosCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestos de venta.
        /// </summary>
        public static string TipoDocumentosPresupuestosVentas {
            get {
                return ResourceManager.GetString("TipoDocumentosPresupuestosVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reservas de compra.
        /// </summary>
        public static string TipoDocumentosReservasCompra {
            get {
                return ResourceManager.GetString("TipoDocumentosReservasCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reservas de ventas.
        /// </summary>
        public static string TipoDocumentosReservasVentas {
            get {
                return ResourceManager.GetString("TipoDocumentosReservasVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de impresión.
        /// </summary>
        public static string Tipoimpresion {
            get {
                return ResourceManager.GetString("Tipoimpresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
    }
}
