//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TablasVarias {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TablasVarias() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.TablasVarias", typeof(TablasVarias).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueo RGPD/LODP.
        /// </summary>
        public static string BloqueoRGPD {
            get {
                return ResourceManager.GetString("BloqueoRGPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo.
        /// </summary>
        public static string Campo {
            get {
                return ResourceManager.GetString("Campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos adicionales.
        /// </summary>
        public static string Camposadicionales {
            get {
                return ResourceManager.GetString("Camposadicionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase.
        /// </summary>
        public static string Clase {
            get {
                return ResourceManager.GetString("Clase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasificación.
        /// </summary>
        public static string Clasificacion {
            get {
                return ResourceManager.GetString("Clasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código ISO 2.
        /// </summary>
        public static string CodigoIsoAlfa2 {
            get {
                return ResourceManager.GetString("CodigoIsoAlfa2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código ISO 3.
        /// </summary>
        public static string CodigoIsoAlfa3 {
            get {
                return ResourceManager.GetString("CodigoIsoAlfa3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cód. ISO Numérico.
        /// </summary>
        public static string CodigoIsoNumerico {
            get {
                return ResourceManager.GetString("CodigoIsoNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste adq..
        /// </summary>
        public static string CosteAdq {
            get {
                return ResourceManager.GetString("CosteAdq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor por defecto.
        /// </summary>
        public static string Defecto {
            get {
                return ResourceManager.GetString("Defecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción 2.
        /// </summary>
        public static string Descripcion2 {
            get {
                return ResourceManager.GetString("Descripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponible.
        /// </summary>
        public static string Disponible {
            get {
                return ResourceManager.GetString("Disponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectivo.
        /// </summary>
        public static string Efectivo {
            get {
                return ResourceManager.GetString("Efectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En almacen.
        /// </summary>
        public static string EnAlmacen {
            get {
                return ResourceManager.GetString("EnAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entradas V..
        /// </summary>
        public static string EntradasV {
            get {
                return ResourceManager.GetString("EntradasV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandato requerido.
        /// </summary>
        public static string MandatoRequerido {
            get {
                return ResourceManager.GetString("MandatoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimiento automático.
        /// </summary>
        public static string MovAutomatico {
            get {
                return ResourceManager.GetString("MovAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nif europeo.
        /// </summary>
        public static string NifEuropeo {
            get {
                return ResourceManager.GetString("NifEuropeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nif obligatorio.
        /// </summary>
        public static string NifObligatorio {
            get {
                return ResourceManager.GetString("NifObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No editable.
        /// </summary>
        public static string Noeditable {
            get {
                return ResourceManager.GetString("Noeditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remesable.
        /// </summary>
        public static string Remesable {
            get {
                return ResourceManager.GetString("Remesable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salidas V..
        /// </summary>
        public static string SalidasV {
            get {
                return ResourceManager.GetString("SalidasV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string TipoTablaConfiguracion {
            get {
                return ResourceManager.GetString("TipoTablaConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contabilidad.
        /// </summary>
        public static string TipoTablaContabilidad {
            get {
                return ResourceManager.GetString("TipoTablaContabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRM.
        /// </summary>
        public static string TipoTablaCRM {
            get {
                return ResourceManager.GetString("TipoTablaCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión.
        /// </summary>
        public static string TipoTablaGestion {
            get {
                return ResourceManager.GetString("TipoTablaGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros.
        /// </summary>
        public static string TipoTablaOtros {
            get {
                return ResourceManager.GetString("TipoTablaOtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producción.
        /// </summary>
        public static string TipoTablaProduccion {
            get {
                return ResourceManager.GetString("TipoTablaProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablas varias.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar valor.
        /// </summary>
        public static string VerificaValor {
            get {
                return ResourceManager.GetString("VerificaValor", resourceCulture);
            }
        }
    }
}
