//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tiposiva {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tiposiva() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Tiposiva", typeof(Tiposiva).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta IVA no deducible.
        /// </summary>
        public static string CtaIvaNoDeducible {
            get {
                return ResourceManager.GetString("CtaIvaNoDeducible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta IVA repercutido.
        /// </summary>
        public static string CtaIvaRepercutido {
            get {
                return ResourceManager.GetString("CtaIvaRepercutido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta IVA repercutido criterio caja.
        /// </summary>
        public static string CtaIvaRepercutidoCriterioCaja {
            get {
                return ResourceManager.GetString("CtaIvaRepercutidoCriterioCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta IVA soportado.
        /// </summary>
        public static string CtaIvaSoportado {
            get {
                return ResourceManager.GetString("CtaIvaSoportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta IVA soportado criterio caja.
        /// </summary>
        public static string CtaIvaSoportadoCriterioCaja {
            get {
                return ResourceManager.GetString("CtaIvaSoportadoCriterioCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta recargo equiv. repercutido.
        /// </summary>
        public static string CtaRecargoEquivalenciaRepercutido {
            get {
                return ResourceManager.GetString("CtaRecargoEquivalenciaRepercutido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta recargo equiv. repercutido criterio caja.
        /// </summary>
        public static string CtaRecargoEquivalenciaRepercutidoCriterioCaja {
            get {
                return ResourceManager.GetString("CtaRecargoEquivalenciaRepercutidoCriterioCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas.
        /// </summary>
        public static string Cuentas {
            get {
                return ResourceManager.GetString("Cuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos de IVA.
        /// </summary>
        public static string GruposIva {
            get {
                return ResourceManager.GetString("GruposIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA deducible.
        /// </summary>
        public static string IvaDeducible {
            get {
                return ResourceManager.GetString("IvaDeducible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iva soportado.
        /// </summary>
        public static string IvaSoportado {
            get {
                return ResourceManager.GetString("IvaSoportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de IVA no pertenece a ningún grupo.
        /// </summary>
        public static string MensajeGruposIva {
            get {
                return ResourceManager.GetString("MensajeGruposIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Deducible.
        /// </summary>
        public static string PorcentajeDeducible {
            get {
                return ResourceManager.GetString("PorcentajeDeducible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % IVA.
        /// </summary>
        public static string PorcentajeIva {
            get {
                return ResourceManager.GetString("PorcentajeIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Recargo equivalencia.
        /// </summary>
        public static string PorcentajeRecargoEquivalencia {
            get {
                return ResourceManager.GetString("PorcentajeRecargoEquivalencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de IVA.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
    }
}
