//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tiposcuentas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tiposcuentas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Tiposcuentas", typeof(Tiposcuentas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de cuenta.
        /// </summary>
        public static string CadenaTipocuenta {
            get {
                return ResourceManager.GetString("CadenaTipocuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contables.
        /// </summary>
        public static string CategoriasCuentasContables {
            get {
                return ResourceManager.GetString("CategoriasCuentasContables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extracontables.
        /// </summary>
        public static string CategoriasCuentasExtracontables {
            get {
                return ResourceManager.GetString("CategoriasCuentasExtracontables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código cuenta.
        /// </summary>
        public static string Cuenta {
            get {
                return ResourceManager.GetString("Cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas asociadas.
        /// </summary>
        public static string CuentasAsociadas {
            get {
                return ResourceManager.GetString("CuentasAsociadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string DescripcionCuenta {
            get {
                return ResourceManager.GetString("DescripcionCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden el Tipo de cuenta actual porque  existen registros asociados a él.
        /// </summary>
        public static string ErrorBorrar {
            get {
                return ResourceManager.GetString("ErrorBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta {0} está duplicada.
        /// </summary>
        public static string ErrorCuentaDuplicada {
            get {
                return ResourceManager.GetString("ErrorCuentaDuplicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta {0} se genera automaticamente en otra tipo de cuenta y podría generaría bucles.
        /// </summary>
        public static string ErrorCuentaLoop {
            get {
                return ResourceManager.GetString("ErrorCuentaLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha encontrado un bucle con la cuenta {0}.
        /// </summary>
        public static string ErrorCuentaLoopEncontrado {
            get {
                return ResourceManager.GetString("ErrorCuentaLoopEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las cuentas extracontables deben empezar con una letra.
        /// </summary>
        public static string ErrorInicioCuentaExtracontable {
            get {
                return ResourceManager.GetString("ErrorInicioCuentaExtracontable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cambiar la Cuenta porque existen registros asociados de tipo {0}.
        /// </summary>
        public static string ErrorUpdateTipoCuenta {
            get {
                return ResourceManager.GetString("ErrorUpdateTipoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nif/Cif obligatorio.
        /// </summary>
        public static string Nifobligatorio {
            get {
                return ResourceManager.GetString("Nifobligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de cuenta.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acreedores.
        /// </summary>
        public static string TiposCuentasAcreedores {
            get {
                return ResourceManager.GetString("TiposCuentasAcreedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agentes.
        /// </summary>
        public static string TiposCuentasAgentes {
            get {
                return ResourceManager.GetString("TiposCuentasAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañías de seguro.
        /// </summary>
        public static string TiposCuentasAseguradoras {
            get {
                return ResourceManager.GetString("TiposCuentasAseguradoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string TiposCuentasClientes {
            get {
                return ResourceManager.GetString("TiposCuentasClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas de tesorería.
        /// </summary>
        public static string TiposCuentasCobradores {
            get {
                return ResourceManager.GetString("TiposCuentasCobradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comerciales.
        /// </summary>
        public static string TiposCuentasComerciales {
            get {
                return ResourceManager.GetString("TiposCuentasComerciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta general.
        /// </summary>
        public static string TiposCuentasGeneral {
            get {
                return ResourceManager.GetString("TiposCuentasGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operarios.
        /// </summary>
        public static string TiposCuentasOperarios {
            get {
                return ResourceManager.GetString("TiposCuentasOperarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prospectos.
        /// </summary>
        public static string TiposCuentasProspectos {
            get {
                return ResourceManager.GetString("TiposCuentasProspectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        public static string TiposCuentasProveedores {
            get {
                return ResourceManager.GetString("TiposCuentasProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportistas.
        /// </summary>
        public static string TiposCuentasTransportistas {
            get {
                return ResourceManager.GetString("TiposCuentasTransportistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de cuentas.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
