//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Unidades {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Unidades() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Unidades", typeof(Unidades).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad.
        /// </summary>
        public static string Codigounidad {
            get {
                return ResourceManager.GetString("Codigounidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimales total.
        /// </summary>
        public static string Decimalestotales {
            get {
                return ResourceManager.GetString("Decimalestotales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion2 {
            get {
                return ResourceManager.GetString("Descripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fórmula.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto corto.
        /// </summary>
        public static string Textocorto {
            get {
                return ResourceManager.GetString("Textocorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto corto.
        /// </summary>
        public static string Textocorto2 {
            get {
                return ResourceManager.GetString("Textocorto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de movimiento.
        /// </summary>
        public static string Tiposmovimientostock {
            get {
                return ResourceManager.GetString("Tiposmovimientostock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote.
        /// </summary>
        public static string TiposStockLote {
            get {
                return ResourceManager.GetString("TiposStockLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string TiposStockMovimientosCantidad {
            get {
                return ResourceManager.GetString("TiposStockMovimientosCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad y total.
        /// </summary>
        public static string TiposStockMovimientosCantidadYTotal {
            get {
                return ResourceManager.GetString("TiposStockMovimientosCantidadYTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string TiposStockMovimientosTotal {
            get {
                return ResourceManager.GetString("TiposStockMovimientosTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unitario.
        /// </summary>
        public static string TiposStockUnitario {
            get {
                return ResourceManager.GetString("TiposStockUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de stock.
        /// </summary>
        public static string Tipostock {
            get {
                return ResourceManager.GetString("Tipostock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string TipoStockFormulasCantidad {
            get {
                return ResourceManager.GetString("TipoStockFormulasCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Linear.
        /// </summary>
        public static string TipoStockFormulasLinear {
            get {
                return ResourceManager.GetString("TipoStockFormulasLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficie.
        /// </summary>
        public static string TipoStockFormulasSuperficie {
            get {
                return ResourceManager.GetString("TipoStockFormulasSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string TipoStockFormulasTotal {
            get {
                return ResourceManager.GetString("TipoStockFormulasTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        public static string TipoStockFormulasVolumen {
            get {
                return ResourceManager.GetString("TipoStockFormulasVolumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculado.
        /// </summary>
        public static string TipoStockTotalCalculado {
            get {
                return ResourceManager.GetString("TipoStockTotalCalculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editado.
        /// </summary>
        public static string TipoStockTotalEditado {
            get {
                return ResourceManager.GetString("TipoStockTotalEditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de total.
        /// </summary>
        public static string Tipototal {
            get {
                return ResourceManager.GetString("Tipototal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
