//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.GeneralUI {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TiposDocumentosContables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TiposDocumentosContables() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.GeneralUI.TiposDocumentosContables", typeof(TiposDocumentosContables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apertura.
        /// </summary>
        public static string EnumApertura {
            get {
                return ResourceManager.GetString("EnumApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apertura provisional.
        /// </summary>
        public static string EnumAperturaProvisional {
            get {
                return ResourceManager.GetString("EnumAperturaProvisional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diario.
        /// </summary>
        public static string EnumAsientos {
            get {
                return ResourceManager.GetString("EnumAsientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asiento vinculado.
        /// </summary>
        public static string EnumAsientoVinculado {
            get {
                return ResourceManager.GetString("EnumAsientoVinculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre.
        /// </summary>
        public static string EnumCierre {
            get {
                return ResourceManager.GetString("EnumCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string EnumNormal {
            get {
                return ResourceManager.GetString("EnumNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regularización de existencias.
        /// </summary>
        public static string EnumRegularizacionExistencias {
            get {
                return ResourceManager.GetString("EnumRegularizacionExistencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regularización de grupos 6 y 7.
        /// </summary>
        public static string EnumRegularizacionGrupos6y7 {
            get {
                return ResourceManager.GetString("EnumRegularizacionGrupos6y7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simulación.
        /// </summary>
        public static string EnumSimulacion {
            get {
                return ResourceManager.GetString("EnumSimulacion", resourceCulture);
            }
        }
    }
}
