//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.GeneralUI {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TiposDocumentos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TiposDocumentos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.GeneralUI.TiposDocumentos", typeof(TiposDocumentos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albaranes de compras.
        /// </summary>
        public static string EnumAlbaranesCompras {
            get {
                return ResourceManager.GetString("EnumAlbaranesCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albaranes de ventas.
        /// </summary>
        public static string EnumAlbaranesVentas {
            get {
                return ResourceManager.GetString("EnumAlbaranesVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entradas varias.
        /// </summary>
        public static string EnumEntradasVarias {
            get {
                return ResourceManager.GetString("EnumEntradasVarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas de compras.
        /// </summary>
        public static string EnumFacturasCompras {
            get {
                return ResourceManager.GetString("EnumFacturasCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas de ventas.
        /// </summary>
        public static string EnumFacturasVentas {
            get {
                return ResourceManager.GetString("EnumFacturasVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos de compras.
        /// </summary>
        public static string EnumPedidosCompras {
            get {
                return ResourceManager.GetString("EnumPedidosCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos de ventas.
        /// </summary>
        public static string EnumPedidosVentas {
            get {
                return ResourceManager.GetString("EnumPedidosVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestos de compras.
        /// </summary>
        public static string EnumPresupuestosCompras {
            get {
                return ResourceManager.GetString("EnumPresupuestosCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestos de ventas.
        /// </summary>
        public static string EnumPresupuestosVentas {
            get {
                return ResourceManager.GetString("EnumPresupuestosVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reservas de stock.
        /// </summary>
        public static string EnumReservas {
            get {
                return ResourceManager.GetString("EnumReservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salidas varias.
        /// </summary>
        public static string EnumSalidasVarias {
            get {
                return ResourceManager.GetString("EnumSalidasVarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traspasos de almacén.
        /// </summary>
        public static string EnumTraspasos {
            get {
                return ResourceManager.GetString("EnumTraspasos", resourceCulture);
            }
        }
    }
}
